---@meta
---@class Barotrauma.Networking.TempClient : System.ValueType
---`Field Public Instance`
---@field Name System.String
---`Field Public Instance`
---@field PreferredJob Barotrauma.Identifier
---`Field Public Instance`
---@field TeamID Barotrauma.CharacterTeamType
---`Field Public Instance`
---@field PreferredTeam Barotrauma.CharacterTeamType
---`Field Public Instance`
---@field NameId System.UInt16
---`Field Public Instance`
---@field AccountInfo Barotrauma.Networking.AccountInfo
---`Field Public Instance`
---@field SessionId System.Byte
---`Field Public Instance`
---@field CharacterId System.UInt16
---`Field Public Instance`
---@field Karma System.Single
---`Field Public Instance`
---@field Muted System.Boolean
---`Field Public Instance`
---@field InGame System.Boolean
---`Field Public Instance`
---@field HasPermissions System.Boolean
---`Field Public Instance`
---@field IsOwner System.Boolean
---`Field Public Instance`
---@field IsDownloading System.Boolean
_G['TempClient'] = {}

